plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    maven {
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        url = "https://maven.teamvoided.org/releases"
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://jitpack.io"
            }
        }
        filter {
            includeGroup "com.github.Chocohead"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft_version}:${parchment_version}@zip")
    }


    modCompileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    modImplementation "net.fabricmc:fabric-loader:${fabric_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modImplementation("com.terraformersmc:modmenu:${modmenu_version}")
    modImplementation "me.fzzyhmstrs:fzzy_config:${fzzy_config_version}"
    modImplementation("com.github.alexthe666.citadel:citadel-1.21.1-refabricated:${fabric_citadel_version}") {
        transitive(false)
    }
    include(modImplementation("com.github.Chocohead:Fabric-ASM:${fabric_asm_version}")) {
        exclude (group: "net.fabricmc.fabric-api")
    }

    // TODO remove when fzzy port
    modApi("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_config_version}")
}

loom {
    accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }

        testWorld {
            client()
            runDir('runs/client')
            programArgs("--quickPlaySingleplayer", "test")
        }

        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

processResources {
    exclude('META-INF/accesstransformer.cfg')
}
