# Project
version=2.0.2
group=com.github.alexscaves
java_version=21
loom_version=1.15-SNAPSHOT
moddev_gradle_version=2.0.140

# Common
minecraft_version=1.21.1
max_minecraft_version=1.21.2
neo_form_version=1.21.1-20240808.144430
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17
fzzy_config_version=0.7.3+1.21
jei_version=19.21.0.247
# TODO remove when fzzy port
fcap_config_version=21.1.6

# Fabric
fabric_version=0.18.4
fabric_api_version=0.116.9+1.21.1
modmenu_version=11.0.3
fabric_citadel_version=2.7.0-alpha.4
fabric_asm_version=v2.3

# NeoForge
neoforge_version=21.1.220
neoforge_loader_version_range=[4,)
neoforge_citadel_version=7476597

# Mod properties
mod_name=Alex's Caves
mod_authors=Alexthe668, Noonyeyz
mod_id=alexscaves
license=GNU LESSER GENERAL PUBLIC LICENSE
description=Explore new rare cave biomes hidden under the surface of the Overworld...

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
