plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

neoForge {
    version = neoforge_version

    accessTransformers.from(project(":common").file('src/main/resources/META-INF/accesstransformer.cfg'))

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }

        client {
            client()
            gameDirectory = project.file('runs/client')
        }

        testWorld {
            client()
            gameDirectory = project.file('runs/client')
            programArguments = ["--quickPlaySingleplayer", "test"]
        }

        server {
            gameDirectory = project.file('runs/server')
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation("curse.maven:citadel-331936:7476597")
    implementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}+neoforge")

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}
